# Generated by Django 4.0.1 on 2022-01-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahadsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='firstCat',
            new_name='Cat',
        ),
        migrations.RemoveField(
            model_name='category',
            name='secondCat',
        ),
        migrations.RemoveField(
            model_name='category',
            name='thirdCat',
        ),
    ]
