# Generated by Django 4.0.1 on 2022-01-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahadsapp', '0002_rename_firstcat_category_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadportfolio',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
