# Generated by Django 4.0.1 on 2022-01-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahadsapp', '0003_uploadportfolio_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadportfolio',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail'),
        ),
        migrations.AlterField(
            model_name='uploadportfolio',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
