# Generated by Django 4.0.1 on 2022-01-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahadsapp', '0004_alter_uploadportfolio_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadportfolio',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
