# Generated by Django 4.0.1 on 2022-01-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahadsapp', '0005_alter_uploadportfolio_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadportfolio',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploadportfolio',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='uploadportfolio',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profiles', verbose_name='Profile Picture'),
        ),
    ]
