# Generated by Django 4.0.1 on 2022-01-24 13:18

from django.db import migrations, models
import fahadsapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fahadsapp', '0007_remove_uploadportfolio_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadportfolio',
            name='ThreeD',
            field=models.FileField(default='', upload_to='3d', validators=[fahadsapp.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
