# Generated by Django 4.0.1 on 2022-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahadsapp', '0009_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ratecl',
            field=models.IntegerField(),
        ),
    ]
