# Generated by Django 4.0.1 on 2022-01-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahadsapp', '0011_alter_client_imgcl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='imgcl',
            field=models.ImageField(default='climg/t1.jpg', upload_to='clientimg'),
        ),
    ]
