# Generated by Django 4.0.1 on 2022-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahadsapp', '0012_alter_client_imgcl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ratecl',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
