# Generated by Django 4.0.1 on 2022-01-26 12:07

from django.db import migrations, models
import fahadsapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fahadsapp', '0013_alter_client_ratecl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadportfolio',
            name='ThreeD',
            field=models.FileField(blank=True, upload_to='3d', validators=[fahadsapp.validators.validate_file_extension]),
        ),
    ]
